stages:
  - test

test_job:
  stage: test
  image: maven:3.8.1-jdk-11  # adjust if you use a different JDK or Maven version
  script:
    - mvn clean verify
  artifacts:
    when: always
    paths:
      - target/site/serenity
    expire_in: 1 week
