stages:
  - test

serenity_tests:
  image: maven:3.9.3-eclipse-temurin-17
  stage: test
  script:
    - mvn clean verify
  artifacts:
    when: always
    paths:
      - target/site/serenity
    expire_in: 1 week
